### ISSUE TITLE
Error - panic: mmap, size 134217728: EDC5132I Not enough memory

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/prometheusport#2]
The first time running Prometheus worked as expected. The second time it failed.
After removing the tsdb, it's able to successfully start up.
Any suggestions?

Our MAXMMAPAREA(131072) is defined in BPXPRMxx (number of pages), which looks to be 500+MB of data space storage.

**First time**
![image](https://github.com/ZOSOpenTools/prometheusport/assets/115715798/cb16c45b-774d-47da-8fb9-e4448563e16e)

**Second time**
![image](https://github.com/ZOSOpenTools/prometheusport/assets/115715798/f8758264-d797-4502-aba5-3a615422a31c)

prometheus.yml
global:
  scrape_interval:     10s
  scrape_timeout:      10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - mvs-sysa.hewitt.com:9090

  - job_name: "demo"
    static_configs:
      - targets:
        - demo.promlabs.com:10000
        - demo.promlabs.com:10001
        - demo.promlabs.com:10002

**Comment by IgorTodorovskiIBM** [comment]
@bluecivet, @jlee3227  do we need a new release with your changes in https://github.com/ZOSOpenTools/prometheusport/pull/1?

**Comment by gngrossi** [comment]
Upgraded and tested several starts/stops along with running some queries...looks good.
thanks
